language: generic 

services:
  - docker

jobs:
  include:
    - stage: compile
      script:
        - exec docker run -a STDOUT -a STDERR --rm -v $(pwd):/ws/src/gps_umd ros:dashing /ws/src/gps_umd/.ros2_build.sh
